### ISSUE TITLE
deodexing

### ISSUE THREAD

**Issue by SeKi81** [MiCode/patchrom_tools#2]
tried to deodex the stock rom from the htc one s. it deodex the complete framework folder without any problem.
But a lot of apps didnt deodexed. -> it has problems to find a resource from the classpath!

**Comment by yu88my** [comment]
can you send me your log file?

---

发件人: Kalashnikitty [reply@reply.github.com]
发送时间: 2012年4月11日 17:57
到: 余明阳
主题: [patchrom_tools] deodexing (#2)

tried to deodex the stock rom from the htc one s. it deodex the complete framework folder without any problem.
But a lot of apps didnt deodexed. -> it has problems to find a resource from the classpath!

---

Reply to this email directly or view it on GitHub:
https://github.com/MiCode/patchrom_tools/issues/2

**Comment by SeKi81** [comment]
okay here is the log: 

pastebin: http://pastebin.com/5xXxJFfS

dropbox: http://dl.dropbox.com/u/15361385/stuff/deodex-log.txt

**Comment by yu88my** [comment]
hi, 
you can try "./deodex.sh  /absolute-path-to-your-stockrom.zip/stockkrom.zip"

---

发件人: Kalashnikitty [reply@reply.github.com]
发送时间: 2012年4月12日 15:43
到: 余明阳
主题: Re: [patchrom_tools] deodexing (#2)

okay here is the log:

pastebin: http://pastebin.com/5xXxJFfS

dropbox: http://dl.dropbox.com/u/15361385/stuff/deodex-log.txt

---

**Comment by SeKi81** [comment]
doesn`t fix that issue :(
